path: modules/

modules:
  - name: config
    exposes:
      - load-config.ts
      - types.ts
    libraries:
      - "@std/yaml/"
      - "node:fs/promises"
      - "zod"

  - name: config-validation
    exposes:
      - mod.ts
    dependsOn:
      - config
    libraries:
      - "@std/collections/"

  - name: structure-validation
    exposes:
      - mod.ts
    dependsOn:
      - config
      - parser
      - core/fs
    libraries:
      - "@std/testing/bdd"
      - "@std/expect/"
      - "@std/path/"

  - name: parser
    description: core parsing logic
    dependsOn:
      - core/types
    exposes:
      - mod.ts
    libraries:
      - "@std/testing/bdd"
      - "@std/expect/"
      - "@swc/wasm"

  - name: cli
    dependsOn:
      - config
      - feature

  - name: feature
    dependsOn:
      - config
      - config-validation
      - structure-validation
      - parser
      - core/fs
    exposes:
      - mod.ts

  - name: core/fs
    dependsOn:
      - config
    exposes:
      - mod.ts
    libraries:
      - "@std/fs/"
      - "@std/path/"

  - name: core/types
    exposes:
      - mod.ts
