path: modules/

modules:
  - name: config
    exposes:
      - types.ts
    libraries:
      - zod

  - name: config-validation
    exposes:
      - mod.ts
    dependsOn:
      - config
    libraries:
      - "@std/collections/"

  - name: structure-validation
    exposes:
      - mod.ts
    dependsOn:
      - config
      - parser
      - core/fs
    libraries:
      - "@std/testing/bdd"
      - "@std/expect/"
      - "@std/path/"

  - name: parser
    description: core parsing logic
    exposes:
      - mod.ts
    libraries:
      - "@std/testing/bdd"
      - "@std/expect/"
      - "@swc/wasm"

  - name: config-reader
    dependsOn:
      - config
    exposes:
      - mod.ts
    libraries:
      - "@std/jsonc/"
      - "@std/yaml/"

  - name: cli
    dependsOn:
      - config-reader
      - feature

  - name: feature
    dependsOn:
      - config
      - config-validation
      - structure-validation
      - parser
      - core/fs
    exposes:
      - mod.ts

  - name: core/fs
    dependsOn:
      - config
    exposes:
      - mod.ts
    libraries:
      - "@std/fs/"
      - "@std/path/"
